#ifndef HTTPDEFINES_H
#define HTTPDEFINES_H



enum class HttpStatusCode
{
    EMPTY = 0,

    CONTINUE = 100,
    SWITCHING_PROTOCOLS = 101,
    PROCESSING = 102,

    OK = 200,
    CREATED = 201,
    ACCEPTED = 202,
    NON_AUTHORITATIVE_INFORMATION = 203,
    NO_CONTENT = 204,
    RESET_CONTENT = 205,
    PARTIAL_CONTENT = 206,
    MULTI_STATUS = 207,

    MULTIPLE_CHOISES = 300,
    MOVED_PERMANENTLY = 301,
    MOVED_TEMPORARILY = 302,
    FOUND = 302,
    SEE_OTHER = 303,
    NOT_MODIFIED = 304,
    USE_PROXY = 305,
    TEMPORARY_REDIRECT = 307,

    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    PAYMENT_REQUIRED = 402,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    methodNOT_ALLOWED = 405,
    NOT_ACCEPTABLE = 406,
    PROXY_AUTHENTICATION_REQUIRED = 407,
    REQUEST_TIMEOUT = 408,
    CONFLICT = 409,
    GONE = 410,
    REQUEST_ENTITY_TOO_LARGE = 413,
    REQUESTED_RANGE_NOT_SATISFIABLE = 416,

    INTERNAL_SERVER_ERROR = 500,
    NOT_IMPLEMENTED = 501,
    BAD_GATEWAY = 502,
    SERVICE_UNAVAILABLE = 503,
    GATEWAY_TIMEOUT = 504,
    HTTP_versionNOT_SUPPORTED = 505,
};

enum class HttpMethod{
    UNDEFINED = 0,
    ANY,
    GET,
    POST,
    HEAD,
    PUT,
    PATCH,
    DELETE,
};

enum class HttpVersion{
    VERSION_1_0,
    VERSION_1_1,
    VERSION_2,
};


inline const char *CRLF="\r\n";

#endif // HTTPDEFINES_H
